// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAo3KOKo1Ya_KHbP-306FWx7xdfQqPp4',
    appId: '1:726854290946:web:206fb4e05ad3479fd2e11b',
    messagingSenderId: '726854290946',
    projectId: 'trading-30a6e',
    authDomain: 'trading-30a6e.firebaseapp.com',
    storageBucket: 'trading-30a6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKoZygypzX_hx8sYlpp9XKYnZFEMwPi6A',
    appId: '1:726854290946:android:f625eb77073fa94ed2e11b',
    messagingSenderId: '726854290946',
    projectId: 'trading-30a6e',
    storageBucket: 'trading-30a6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkujxXmJZTwBYWST6ogqJ8kmlaY65lO2E',
    appId: '1:726854290946:ios:2857646da4fe7121d2e11b',
    messagingSenderId: '726854290946',
    projectId: 'trading-30a6e',
    storageBucket: 'trading-30a6e.firebasestorage.app',
    iosBundleId: 'com.example.tradingApp',
  );
}
